### ISSUE TITLE
Descuento de Monedas

### ISSUE THREAD

**Issue by NehemiasMercau** [Capa-8/ProjectClicker#10]
> Cuando un enemigo aparezca, que descuente monedas únicamente cuando no se lo pudo vencer

> Cuando un enemigo aparece y no se le pude ganar, que recién ahí descuente monedas

**Comment by F96G** [comment]
> > Cuando un enemigo aparezca, que descuente monedas únicamente cuando no se lo pudo vencer
> Finalice esta funcionalidad y funciona correctamente
> > Cuando un enemigo aparece y no se le pude ganar, que recién ahí descuente monedas
